version: '3.7'

services:
  pyserver:
    container_name: pyserver
    ports:
      - ${PORT_DEV_REMOTE_DEBUG}:${PORT_DEV_REMOTE_DEBUG}
    networks:
      frontend:

  grafana:
    ports:
      - ${PORT_GRAFANA}:${PORT_GRAFANA}
    networks:
      frontend:

  kibana:
    ports:
      - ${PORT_KIBANA}:${PORT_KIBANA}
    networks:
      frontend:

  logstash:
    volumes:
      - /mnt/usb1/docker:/var/lib/docker:ro

networks:
  frontend:
