networks:
  backend: {}
  frontend: {}
services:
  elasticsearch:
    cap_add:
    - IPC_LOCK
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      node.name: SolarHome
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0-arm64
    networks:
      backend: {}
    ports:
    - published: 9200
      target: 9200
    restart: always
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - datasolar01:/usr/share/elasticsearch/data:rw
  grafana:
    build:
      context: /workspaces/HomeAssiWithSolar
      dockerfile: ./docker/Dockerfile.grafana
    container_name: grafana
    environment:
      PORT_ELASTIC_1: '9200'
    image: grafana
    networks:
      backend: {}
      frontend: {}
    ports:
    - published: 3000
      target: 3000
    restart: always
    volumes:
    - /workspaces/HomeAssiWithSolar/docker/dashboards/json:/etc/dashboards:rw
    - /workspaces/HomeAssiWithSolar/docker/dashboards:/etc/grafana/provisioning/dashboards:rw
    - /workspaces/HomeAssiWithSolar/docker/datasources:/etc/grafana/provisioning/datasources:rw
  kibana:
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    image: jamesgarside/kibana:7.12.0
    links:
    - elasticsearch
    networks:
      backend: {}
      frontend: {}
    ports:
    - published: 5601
      target: 5601
    restart: always
  logstash:
    build:
      context: /workspaces/HomeAssiWithSolar
      dockerfile: ./docker/Dockerfile.logstash
    container_name: logstash
    environment:
      PORT_ELASTIC_1: '9200'
    image: logstash
    networks:
      backend: {}
    ports:
    - published: 5044
      target: 5044
    volumes:
    - /mnt/usb1/docker:/var/lib/docker:ro
  pyserver:
    build:
      context: /workspaces/HomeAssiWithSolar
      dockerfile: ./docker/Dockerfile.pyserver
    container_name: pyserver
    entrypoint:
    - python3
    - -m
    - debugpy
    - --listen
    - 0.0.0.0:5678
    - ./main.py
    environment:
      PORT_ELASTIC_1: '9200'
    image: pyserver
    networks:
      backend: {}
      frontend: {}
    ports:
    - published: 5678
      target: 5678
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /workspaces/HomeAssiWithSolar/src/pyserver:/usr/src/pyserver:rw
version: '3.7'
volumes:
  datasolar01:
    driver: local
    driver_opts:
      device: /mnt/usb1/storagehome
      o: bind
      type: volume

