version: '3.7'

services: 
  hello_world:
      image: hello-world:latest
      networks:
        backend:
          ipv4_address: ${IPV4_HELLO_WORLD} 

networks:
  backend:
    ipam:
      config:
        - subnet: ${IPV4_SUBNET}
