:toc:
:icons: font
:experimental:
:source-highlighter: pygments
// :pygments-style: emacs

= Set up a dashboard with a Modbus communication to a SolarEdge system

== working with this project

=== initial

* https://code.visualstudio.com/download[VSC] with https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Remote-Containers]

* https://docs.docker.com/docker-for-windows/install-windows-home/[docker on Windows]

.https://www.ssh.com/ssh/keygen/[Copying the Public Key to the Server]
[source, bash]
----
ssh-copy-id -i ~/.ssh/id_rsa.pub user@host
----

[NOTE]

In the Section <<devContainer>> you can see how to go into a development container. The ``ssh-copy-id``-command is working from inside the development container. Now you can ssh from the development container to your Host/Pi/...

=== basic commands

.freeze python requirements
[source, BASH]
----
pip freeze > docker/requirements.txt
----

.start docker container from #outside# the devContainer
[source, CMD]
----
docker-compose -f ./docker-compose.yml up --build --force-recreate -d
----

.stop docker container
[source, BASH]
----
docker-compose -f ./docker-compose.yml down
----

=== devContainer
.creat an network for the developing container if it is not existing already. (e.g. docker-compose wasn't executed before)
[source, cmd]
----
docker-compose -f ./docker-compose.network.yml up
----

.load development Container in VSC
. kbd:[Ctrl+Shift+P] or kbd:[F1]
. type in : ``Remote-Containers: Reopen in Container``

[IMPORTANT]
The Extension https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Remote-Containers] is needed

=== overview of environment

.overview of environment variables in the project
[subs="attributes"]
----
include::.env[]
----

=== Additional USB Data Storage

. Find out the UUID of the USB Storage
+
[source, bash]
----
sudo blkid
----
+
. Make a directory for the USB Storage
+
[source, bash]
----
sudo mkdir /mnt/usb1
----

+
. Editing "fstab" file for auto-mounting the USB Storage
+
[source, bash]
----
sudo nano /etc/fstab
----
+
adding the follow line in the file (with your UUID)
+
[source, bash]
----
UUID="f8f8ba1c-7dfd-45ff-b8dc-730b576f4344" /mnt/usb1 ext4 defaults,auto,rw,nofail,exec 0 0
----
+
. read fstab with
+
[source, bash]
----
sudo mount -a
----
+

https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux

== Link collection

https://www.home-assistant.io/installation/raspberrypi[Home Assistant on Rpi with docker]

https://github.com/binsentsu/home-assistant-solaredge-modbus[modbus rpi - home assistant]

https://github.com/erikarenhill/solaredge-modbus-hass[Modbus SolarEdge for homeassi] from https://community.home-assistant.io/t/custom-component-solaredge-modbus-tcp/165625[Forum]

https://www.photovoltaikforum.com/thread/120980-akkustand-per-modbus-tcp-auslesen-solaredge-lg-resu-10h/[ModBus Register für RESU 10h] with https://www.photovoltaikforum.com/thread/120980-akkustand-per-modbus-tcp-auslesen-solaredge-lg-resu-10h/?pageNo=8[overview - jpeg]

https://www.photovoltaikforum.com/thread/137180-solaredge-setapp-version-modbus-via-tcp/?pageNo=3[optimizer Data] 

https://www.photovoltaikforum.com/thread/120980-akkustand-per-modbus-tcp-auslesen-solaredge-lg-resu-10h/?pageNo=8[Battery-Register]

== commands on Raspi

.from laptop to Raspberry pi
[source, bash]
----
rsync -r /workspaces/HomeAssiWithSolar/ ubuntu@192.168.178.3:/mnt/usb1/homeassi/ --delete --exclude "SSH"
----

.add local bind-mounts. Makes Hot-deployment possible
[source, bash]
----
docker-compose -f ./docker-compose.yml -f ./docker-compose.local.yml -f ./docker-compose.arm.yml -f ./docker-compose.prod.yml up --build --force-recreate -d
----

== python

https://pypi.org/project/pyModbusTCP/[Python lib for Modbus]


== to do

https://github.com/nmakel/solaredge_modbus[SolarEdge Modbus on GitHub with influxDB]


https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket[add group]

