{
 "title": "Solar_House",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Power values ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "I_AC_Power",
       "hide": false,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "I_DC_Power",
       "hide": false,
       "id": "3",
       "type": "avg"
      },
      {
       "field": "M_AC_Power",
       "hide": false,
       "id": "4",
       "type": "avg"
      },
      {
       "field": "calc_consumption_power",
       "hide": false,
       "id": "5",
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "I_AC_Frequency", "id": "1", "type": "avg" },
      { "field": "M_AC_Freq", "id": "3", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "I_Temp_Sink", "id": "1", "type": "avg" },
      { "field": "Average_Temperature", "id": "3", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}